/**
 * Doc Finder platform data (from Dev Doc Tool).
 * Loaded by popup.html and used by popup.js.
 */
const DOC_FINDER_PLATFORMS = [
  {
    id: 'magento2',
    label: 'Magento 2',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501659217179-Magento-2-Added-to-Cart-Troubleshooting', text: 'Add To Cart' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501660074267-Magento-2-Troubleshooting-Hub#missingstartedcheckoutmetrics', text: 'Started Checkout' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501680854555-Magento-2-Order-Event-Requirements', text: 'Order Requirements' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501660074267-Magento-2-Troubleshooting-Hub#missingviewedproductmetrics', text: 'Viewed Product' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/sections/18186074970267-Catalog-Troubleshooting-Magento-2', text: 'Catalog Issues' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501680341403-Magento-2-Integration-Level-Configurable-Options', text: 'Configure Integration' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18588253992859-Historical-Syncs-FAQ', text: 'Historical Sync FAQ' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/23339012292123-Magento-2-REST-API-Endpoints-for-PostmanLite', text: 'PostmanLite' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/20203160967707-Magento-2-How-to-Troubleshoot-Periodic-Syncs-Running-on-Sync-2', text: 'Periodic Sync' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501659271579-Magento-2-Subscriber-Consent-Issues', text: 'Subscribe & Consent' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/sections/18185388049435-Magento-2-OAuth-Troubleshooting', text: 'Setup & OAuth' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501659351067-Troubleshooting-Magento-2-Coupons#troubleshootingscenarios', text: 'Coupons' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501660074267-Magento-2-Troubleshooting-Hub#overview', text: 'All Issues' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/115005254348', text: 'Help Center' },
    ],
  },
  {
    id: 'developer',
    label: 'Developer Portal',
    links: [
      { url: 'https://developers.klaviyo.com/en/docs/api_overview', text: 'API Overview' },
      { url: 'https://developers.klaviyo.com/en/docs/get_started', text: 'Get Started' },
      { url: 'https://developers.klaviyo.com/en/docs/sdk_overview', text: 'SDK Overview' },
      { url: 'https://developers.klaviyo.com/en/reference', text: 'API Reference' },
      { url: 'https://developers.klaviyo.com/en/docs', text: 'Docs Home' },
    ],
  },
  {
    id: 'bigcommerce',
    label: 'BigCommerce',
    links: [
      { url: 'https://help.klaviyo.com/hc/en-us/articles/360024310292', text: 'Add To Cart' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/360022594552-How-to-add-a-Klaviyo-embedded-form-to-your-BigCommerce-site', text: 'Embed Form' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/360031724251-How-to-embed-a-sign-up-form-on-your-order-confirmation-page', text: 'Embed - Conf Page' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/360022884472', text: 'Coupons' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/360025079491', text: 'Install Back In stock' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3503849477/BigCommerce+Integration+Troubleshooting+Guide#Back-in-Stock', text: 'BIS - Variants' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501579075099-BigCommerce-Integration-Level-Configurable-Options', text: 'Configurable Options' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3503849477/BigCommerce+Integration+Troubleshooting+Guide#Missing-Events', text: 'Missing Events' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18588253992859-Historical-Syncs-FAQ', text: 'Historical Sync FAQ' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501558147099-Troubleshooting-BigCommerce-Catalog-', text: 'Catalog' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18589298669851-Order-Status-Placed-Order-Events#bigcommerce', text: 'Order Events' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/SA/pages/3995107350/BigCommerce+Errant+Started+Checkout+Events', text: 'Started Checkout' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/1081278542/BigCommerce+-+Subscribe+New+Store+Account+to+a+List', text: 'Account Sign up' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/115005082747-How-to-add-a-link-that-applies-an-item-to-a-BigCommerce-cart', text: 'Link Item In Cart Email' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/PC/pages/1867814/Integration+Troubleshooting#IntegrationTroubleshooting-BigCommerce', text: 'Integration Authorisation' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501558210587-BigCommerce-Integration-fails-and-cannot-be-removed', text: 'Integration Fails' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501579001371-BigCommerce-Integration-Troubleshooting-Guide', text: 'Integration Error' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3264184465/BigCommerce', text: 'All Other Issues' },
    ],
  },
  {
    id: 'woocommerce',
    label: 'WooCommerce',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501781074843-Troubleshooting-Guide-WooCommerce#howtocheckforextensionversion', text: 'Check Extension' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501781074843-Troubleshooting-Guide-WooCommerce#initialsetup:', text: 'Integration Setup' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501781074843-Troubleshooting-Guide-WooCommerce#missing/incorrectevents', text: 'Missing Events' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18588253992859-Historical-Syncs-FAQ', text: 'Historical Sync FAQ' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759774875-How-To-Woocommerce-Inspector-Tasks', text: 'Inspector Tasks' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501780798747-WooCommerce-Integration-Level-Configurable-Options', text: 'Configurable Options' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/EN/pages/2991260144/WooCommerce+3rd+party+Plugins', text: '3rd Party Plugins' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759528987-WooCommerce-Catalog-Troubleshooting', text: 'Catalog' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/360031279471-How-to-set-up-coupons-for-WooCommerce', text: 'Coupons' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759997083-Woocommerce-Order-Event-Requirements', text: 'Event Requirements' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/360030732832-WooCommerce-data-reference', text: 'Data Sync Reference' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501780597275-Woocommerce-Hooks-and-Filters', text: 'Extend Plugin' },
      { url: 'https://klaviyo.zendesk.com/hc/en-us/articles/360035540251-Understanding-how-to-use-WooCommerce-subscriptions-data-in-campaigns-and-flows', text: 'Subscription Data' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759640091-WooCommerce-duplicate-Started-Checkouts-solution-for-plugin-v3-0-9-', text: 'Dupliacte Checkout' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/19884262056219-Cloudflare-Errors-Integrations', text: 'Sync Issue - Cloudfare' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501781074843-Troubleshooting-Guide-WooCommerce#otherissues', text: 'All Other Issues' },
    ],
  },
  {
    id: 'prestashop',
    label: 'PrestaShop',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501697015707-PrestaShop-Integration-Troubleshooting-Guide#issuessyncingevents', text: 'Integration Setup' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501697015707-PrestaShop-Integration-Troubleshooting-Guide#issuessyncingevents', text: 'Events Syncing' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501684060443-Troubleshooting-Prestashop-Catalog', text: 'Catalog' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3672801528/PrestaShop+VAT+tax+Inclusive+Price+Feature', text: 'VAT' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501696942107-PrestaShop-Integration-Level-Configurable-Options', text: 'Configurable Options' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501684390811-PrestaShop-Order-Event-Requirements', text: 'Order Events' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501684145307-PrestaShop-Inspector-Tasks', text: 'Inspector Tasks' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3458990200/E-Commerce+Integrations+General', text: 'Integrations General' },
      { url: 'https://help.klaviyo.com/hc/en-us/sections/360011681092', text: 'Help Center' },
    ],
  },
  {
    id: 'salesforcecc',
    label: 'Salesforce CC',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18586591711771-Salesforce-Commerce-Cloud-SFCC-Troubleshooting', text: 'General' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501737130139-Salesforce-Commerce-Cloud-SFCC-Integration-Errors', text: 'Integration Errors' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501699394331-Salesforce-Commerce-Cloud-Catalog-Troubleshooting', text: 'Catalog' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501684390811-PrestaShop-Order-Event-Requirements', text: 'Order Events' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3071279239/Salesforce+Commerce+Cloud+Order+Event+Requirements', text: 'Cloud Order' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501699655963-Salesforce-Commerce-Cloud-SFCC-Integration-Level-Configurable-Options', text: 'Configurable Options' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501738286235-SFCC-Catalog-How-to-sync-additional-categories', text: 'Additional Categories' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/21349090356507-Salesforce-Commerce-Cloud-SFCC-Inspector-Tasks', text: 'Inspector Tasks' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501738348315-SFCC-Catalog-Troubleshooting-Product-URL-Override', text: 'URL Override' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501560267931-Clearing-SFCC-Catalog-to-only-use-a-custom-catalog', text: 'Custom Catalog' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501738407067-SFCC-Catalog-Troubleshooting-product-image-mapping', text: 'Image Mapping' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/2613936266/Integration+QA+Guide+for+SFCC', text: 'QA Guide' },
      { url: 'https://help.klaviyo.com/hc/en-us/sections/360007844051', text: 'Help Centre' },
    ],
  },
  {
    id: 'shopify',
    label: 'Shopify',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501701609627-Troubleshooting-Guide-Shopify-Added-to-Cart-DevTools', text: 'Add To Cart' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739526299-Troubleshooting-Guide-Shopify-Integration#duplicateklaviyo.jsscriptinstalledonasingleshopifysite', text: 'Duplicated Klaviyo JS' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18912284898331-Troubleshooting-Shopify-3rd-party-Apps-On-Site-tracking', text: 'On Site Conflicts' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739082651-Troubleshooting-Guide-Shopify-3rd-party-Apps-that-can-interfere-with-Tracking', text: 'ATC Conflicts' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501738833307-Troubleshooting-Guide-Shopify-Catalog', text: 'Catalog' },
      { url: 'https://klaviyo.atlassian.net/wiki/spaces/TRC/pages/3071115451/Shopify+Order+Event+Requirements', text: 'Order Event Reqs' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18911919632667-Shopify-Viewed-Product-Tracking-for-Variant-Products', text: 'Variant Tracking' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739604123-Shopify-Integration-Level-Configurable-Options', text: 'Inspector Tasks' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/18588253992859-Historical-Syncs-FAQ', text: 'Historical Sync FAQ' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739526299-Troubleshooting-Guide-Shopify-Integration#historicalsyncstuckornotsyncing', text: 'Historical Sync' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739526299-Troubleshooting-Guide-Shopify-Integration#customizingproducturlsintheproductblock', text: 'Product URLs' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501755979163-How-To-Tracking-Inventory-Published-Un-Published-Products', text: 'Product Publishing' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/16628853835547-Troubleshooting-Guide-Shopify-Subscribers-Sync', text: 'Subscribe & Consent' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501701699355-Troubleshooting-Guide-Shopify-Checkout-URL-Behavior', text: 'Checkout URL' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/17814602332443-Troubleshooting-Shopify-Coupons', text: 'Coupons' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739526299-Troubleshooting-Guide-Shopify-Integration#howtotrackothereventsandcustompropertiesfromshopifyintoklaviyo:', text: 'Shopify Flows' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501739526299-Troubleshooting-Guide-Shopify-Integration#integrationissues/errors', text: 'All Other Issues' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/4403927899291', text: 'Help Center' },
    ],
  },
  {
    id: 'facebook',
    label: 'Facebook',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/32432369530779-Meta-Facebook-Ads-Troubleshooting#customaudienceissues(klaviyo-%3Emeta)', text: 'Custom Audience Issues' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/32432369530779-Meta-Facebook-Ads-Troubleshooting#leadadsissues(meta-%3Eklaviyo)', text: 'Lead Ad Issues' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/32432369530779-Meta-Facebook-Ads-Troubleshooting#lesscommonreasonscustomershiterrorsinintegrationsettings', text: 'Staffside Errors' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/21380882095515-How-to-Make-Meta-Facebook-API-Calls-in-Staffside-via-PostmanLite', text: 'Facebook Graph API' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/115005082127', text: 'Help Center' },
    ],
  },
  {
    id: 'wix',
    label: 'Wix',
    links: [
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759384603-Troubleshooting-Wix-Integration#integrationerrors', text: 'Integration errors' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759384603-Troubleshooting-Wix-Integration#subscriber/formissues', text: 'Form issues' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759384603-Troubleshooting-Wix-Integration#productfeed/catalogissues', text: 'Product issues' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759384603-Troubleshooting-Wix-Integration#missingdata', text: 'Missing Data' },
      { url: 'https://klaviyo-internal-kb.zendesk.com/hc/en-us/articles/15501759313179-Wix-Inspector-Tasks', text: 'Inspector Tasks' },
      { url: 'https://help.klaviyo.com/hc/en-us/articles/6202669053723', text: 'Help Center' },
    ],
  },
];
